"""PDF Report Builder — generates portfolio + chat reports as PDF."""

from __future__ import annotations

import re
from fpdf import FPDF
from app.services.portfolio_data import PortfolioData, AllocationRow, PersonalContext
from app.services.insight_engine import Insight
from app.services.health_score import compute_health_score


def _safe(text: str) -> str:
    """Replace Unicode characters unsupported by built-in PDF fonts."""
    chars = {
        "—": "-", "–": "-", "‘": "'", "’": "'",
        "“": '"', "”": '"', "…": "...", " ": " ",
        "•": "-", "™": "", "®": "",
        "\U0001f44d": "[+]", "\U0001f44e": "[-]", "\U0001f4a1": "[i]",
        "\U0001f4b0": "[$]", "\U0001f534": "[!]", "\U0001f7e2": "[+]",
        "\U0001f7e1": "[!]", "\U0001f535": "[!]", "\U0001f4ac": "",
        "\U0001f3af": "", "\U0001f464": "",
    }
    for k, v in chars.items():
        text = text.replace(k, v)
    # Strip remaining non-latin-1 characters
    result = []
    for ch in text:
        try:
            ch.encode("latin-1")
            result.append(ch)
        except UnicodeEncodeError:
            result.append("?")
    return "".join(result)


# ── Helpers ────────────────────────────────────────────────────────

def _strip_markdown(text: str) -> str:
    """Convert basic markdown to plain text suitable for PDF rendering."""
    # Remove headers
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    # Bold/italic
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"__(.+?)__", r"\1", text)
    text = re.sub(r"_(.+?)_", r"\1", text)
    # Inline code
    text = re.sub(r"`([^`]+)`", r"\1", text)
    # Bullet points
    text = re.sub(r"^\s*[-*+]\s+", "  • ", text, flags=re.MULTILINE)
    # Numbered lists — keep numbers
    text = re.sub(r"^\s*\d+\.\s+", "  ", text, flags=re.MULTILINE)
    # Horizontal rules
    text = re.sub(r"^[-*_]{3,}\s*$", "", text, flags=re.MULTILINE)
    # Collapse multiple blank lines
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


# ── PDF Builder ────────────────────────────────────────────────────

class PDFReport(FPDF):
    """Custom FPDF subclass with helper methods for the wealthwise report."""

    def __init__(self):
        super().__init__("P", "mm", "A4")
        self.set_auto_page_break(True, 20)
        self.add_page()
        # Title at top of first page
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(59, 130, 246)
        self.cell(0, 8, _safe("Wealthwise - Portfolio Report"), new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 4, "Generated by Wealthwise", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    # ── Layout helpers ───────────────────────────────────────────

    def _section_title(self, title: str):
        self.ln(4)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 58, 95)
        self.cell(0, 8, _safe(title), new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(59, 130, 246)
        self.set_line_width(0.6)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def _sub_title(self, title: str):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(71, 85, 105)
        self.cell(0, 6, _safe(title), new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def _body(self, text: str, size: int = 9):
        self.set_font("Helvetica", "", size)
        self.set_text_color(30, 41, 59)
        self.multi_cell(0, 4.5, _safe(text), new_x="LMARGIN", new_y="NEXT")

    def _key_value(self, key: str, value: str, w: float = 50):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(71, 85, 105)
        self.cell(w, 5, _safe(key))
        self.set_font("Helvetica", "", 9)
        self.set_text_color(30, 41, 59)
        self.cell(0, 5, _safe(value), new_x="LMARGIN", new_y="NEXT")

    def _metric_row(self, metrics: list[tuple[str, str]]):
        """Render 2-4 metric boxes in a row."""
        n = len(metrics)
        col_w = (self.w - self.l_margin - self.r_margin) / n
        for label, value in metrics:
            self.set_font("Helvetica", "", 7)
            self.set_text_color(100, 116, 139)
            x = self.get_x()
            y = self.get_y()
            self.cell(col_w, 3.5, label)
            self.set_xy(x, y + 3.5)
            self.set_font("Helvetica", "B", 11)
            self.set_text_color(30, 41, 59)
            self.cell(col_w, 6, value)
            self.set_xy(x, y)
            self.set_x(self.get_x() + col_w)
        self.ln(12)

    def _table_header(self, cols: list[tuple[str, float]]):
        """Draw table header row.  cols = [(label, width_mm), ...]."""
        self.set_fill_color(241, 245, 249)
        self.set_font("Helvetica", "B", 7.5)
        self.set_text_color(71, 85, 105)
        for label, w in cols:
            self.cell(w, 5.5, label, border=0, fill=True)
        self.ln()

    def _table_row(self, cells: list[str], widths: list[float], fill: bool = False):
        if fill:
            self.set_fill_color(248, 250, 252)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(30, 41, 59)
        for text, w in zip(cells, widths):
            self.cell(w, 5, _safe(text), border=0, fill=fill)
        self.ln()

    # ── Section builders ──────────────────────────────────────────

    def add_personal_context(self, p: PersonalContext):
        self._section_title("Personal Profile")
        self._key_value("Age:", str(p.age))
        self._key_value("Risk tolerance:", p.risk_tolerance.title())
        self._key_value("Investment horizon:", p.investment_horizon)
        self._key_value("Primary goal:", p.primary_goal.title())
        self._key_value("Income band:", p.income_band)
        self._key_value("Tax band:", p.tax_band.replace("_", " ").title())
        self._key_value("Pension contributions:", f"£{p.pension_contributions_monthly:,}/mo")
        self._key_value("ISA contributions:", f"£{p.isa_contributions_monthly:,}/mo")

    def add_portfolio_summary(self, data: PortfolioData):
        self._section_title("Portfolio Summary")
        is_gain = data.total_gain_loss >= 0
        sign = "+" if is_gain else ""
        gain_str = f"£{data.total_gain_loss:,.0f} ({sign}{data.total_gain_loss_pct:.1f}%)"
        self._metric_row([
            ("Total value", f"£{data.total_value:,.0f}"),
            ("Total cost", f"£{data.total_cost:,.0f}"),
            ("Gain / Loss", gain_str),
            ("Accounts", str(len(data.accounts))),
            ("Holdings", str(len(data.all_holdings()))),
        ])

    def add_accounts_detail(self, data: PortfolioData):
        self._section_title("Accounts & Holdings")
        cols = [("Holding", 62), ("Asset class", 24), ("Sector", 28),
                ("Geography", 22), ("Value", 22), ("Gain/Loss", 22)]
        widths = [c[1] for c in cols]

        for acc in data.accounts:
            self._sub_title(
                f"{acc.provider} — {acc.account_type}  "
                f"(Total £{acc.total_value:,.0f}, Cash £{acc.cash_balance:,.0f})"
            )
            if not acc.holdings:
                self._body("No holdings", 8)
                continue

            self._table_header(cols)
            for i, h in enumerate(acc.holdings):
                is_gain = h.gain_loss_gbp >= 0
                sign = "+" if is_gain else ""
                cells = [
                    f"{h.name} {h.ticker or ''}".strip(),
                    h.asset_class.replace("_", " ").title(),
                    h.sector.replace("_", " ").title(),
                    h.geography.replace("_", " ").title(),
                    f"£{h.value_gbp:,.0f}",
                    f"{sign}{h.gain_loss_pct:.1f}%",
                ]
                self._table_row(cells, widths, fill=(i % 2 == 1))
            self.ln(2)

    def add_allocations(
        self,
        asset: list[AllocationRow],
        sector: list[AllocationRow],
        geo: list[AllocationRow],
    ):
        self._section_title("Allocations")
        cols = [("Category", 70), ("Value", 35), ("Allocation", 35)]
        widths = [c[1] for c in cols]
        for title, rows in [("Asset Class", asset), ("Sector", sector), ("Geography", geo)]:
            self._sub_title(title)
            if not rows:
                self._body("No data", 8)
                continue
            self._table_header(cols)
            for i, r in enumerate(rows):
                self._table_row(
                    [r.label, f"£{r.value_gbp:,.0f}", f"{r.percentage:.1f}%"],
                    widths, fill=(i % 2 == 1),
                )
            self.ln(2)

    def add_health_score(self, report: dict):
        self._section_title("Portfolio Health")
        grade = report["grade"]
        # Grade box
        self.set_font("Helvetica", "B", 22)
        self.set_text_color(30, 58, 95)
        self.cell(14, 8, grade)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, f"{report['overall']}/10", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        for dim in report["dimensions"]:
            bar_w = 100
            self.set_font("Helvetica", "", 8)
            self.set_text_color(71, 85, 105)
            self.cell(40, 4.5, dim["dimension"])
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(30, 41, 59)
            self.cell(10, 4.5, f"{dim['score']:.0f}")
            # Draw bar
            x0 = self.get_x()
            y0 = self.get_y() + 1
            fill_w = bar_w * dim["score"] / 10
            self.set_fill_color(226, 232, 240)
            self.rect(x0, y0, bar_w, 3, style="F")
            self.set_fill_color(59, 130, 246)
            self.rect(x0, y0, fill_w, 3, style="F")
            self.set_x(x0 + bar_w + 2)
            self.ln(5.5)

        if report["top_findings"]:
            self.ln(2)
            self._sub_title("Top Findings")
            for f in report["top_findings"]:
                self._body(f"• {f['dimension']}: {f['summary']}", 8)

    def add_insights(self, insights: list[Insight]):
        if not insights:
            return
        self._section_title("Portfolio Insights")
        for i in insights:
            self._body(f"{i.emoji}  {i.label}", 9)

    def add_chat_history(self, messages: list[dict]):
        if not messages:
            return
        self._section_title("Chat History")
        for msg in messages:
            role = msg.get("role", "user")
            content = _safe(_strip_markdown(msg.get("content", "")))
            if not content:
                continue
            if role == "user":
                self.set_font("Helvetica", "B", 8)
                self.set_text_color(30, 64, 175)
                self.cell(0, 4, "You", new_x="LMARGIN", new_y="NEXT")
                self.set_font("Helvetica", "", 8)
                self.set_text_color(30, 41, 59)
                self.multi_cell(0, 4, content, new_x="LMARGIN", new_y="NEXT")
            else:
                self.set_font("Helvetica", "B", 8)
                self.set_text_color(100, 116, 139)
                self.cell(0, 4, "Wealthwise", new_x="LMARGIN", new_y="NEXT")
                self.set_font("Helvetica", "", 8)
                self.set_text_color(30, 41, 59)
                self.multi_cell(0, 4, content, new_x="LMARGIN", new_y="NEXT")
            self.ln(2)

    # ── Build ─────────────────────────────────────────────────────

    def build(self) -> bytes:
        """Return the complete PDF as bytes."""
        return self.output()
